---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/index.md
  label: Home
  match: "**/*"
- type: document
  path: src/focus-areas.md
  label: Focus Areas
  match: "**/*"
- type: document
  path: src/about-us.md
  label: About Us
  match: "**/*"
- type: document
  path: src/grants-and-partnerships.md
  label: Grants & Partnerships
  match: "**/*"
- type: document
  path: src/news.md
  label: News
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
